version: '3.5'

volumes:
  elasticsearch:
    driver: ${VOLUMES_DRIVER}

services:
    backend:
      build: ./SimpleApp/
      ports:
        - "5000:5000"
### NGINX Server #########################################
    nginx:
      image: nginx:alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - backend
      ports:
        - "4000:4000"

### MongoDB ##############################################
    mongo:
      build: ./mongo
      ports:
        - "${MONGODB_PORT}:27017"

### ElasticSearch ########################################
    elasticsearch:
      build:
        context: ./elasticsearch
        args:
          - ELK_VERSION=${ELK_VERSION}
      volumes:
        - elasticsearch:/usr/share/elasticsearch/data
      environment:
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - cluster.routing.allocation.disk.threshold_enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"

    ### Grafana ################################################
    grafana:
      build:
        context: ./grafana
      volumes:
        - ${DATA_PATH_HOST}/grafana:/var/lib/grafana
      ports:
        - "${GRAFANA_PORT}:3000"
      user: "0"
      links:
        - influxdb

    influxdb:
      image: influxdb:1.7
      container_name: influxdb
      ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
        - "2003:2003"
      environment:
        - INFLUXDB_DATA_ENGINE=tsm1
        - INFLUXDB_REPORTING_DISABLED=false
        - INFLUXDB_GRAPHITE_0_ENABLED=true
        - INFLUXDB_GRAPHITE_0_DATABASE=graphite
        - INFLUXDB_GRAPHITE_0_BIND_ADDRESS=:2003
        - INFLUXDB_GRAPHITE_PROTOCOL=tcp
        - INFLUXDB_GRAPHITE_BATCH_SIZE=1000
      volumes:
        # Data persistency
        # sudo mkdir -p /srv/docker/influxdb/data
        - /srv/docker/influxdb/data:/var/lib/influxdb

    telegraf:
      image: telegraf:latest
      container_name: telegraf
      links:
        - influxdb
        - elasticsearch
        - nginx
        - mongo
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /var/run/docker.sock:/var/run/docker.sock